name: Sync Repositories

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  sync_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo (jman1593.github.io)
      uses: actions/checkout@v3
      with:
        repository: jman1593/jman1593.github.io
        ref: test
        path: source_repo
        token: ${{ secrets.TOKEN }}  # Use the PAT here for private repo access

    - name: Checkout target repo (strongdog2)
      uses: actions/checkout@v3
      with:
        repository: jman1593/strongdog2
        ref: test
        path: target_repo
        token: ${{ secrets.TOKEN }}  # Use the PAT here for private repo access

    - name: Ensure source_repo exists
      run: |
        if [ ! -d "source_repo" ]; then
          echo "Source repository directory not found!"
          exit 1
        fi

    - name: Sync files (excluding specific folders and files)
      run: |
        rsync -av --exclude='html/' --exclude='img/' --exclude='swf/' --exclude='.github/' \
                  --exclude='secret-menu.html' --exclude='cards_data.html' source_repo/ target_repo/
                  
    - name: Commit and push changes to strongdog2
      working-directory: target_repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Check if there are any changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Sync changes from jman1593.github.io repo"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/jman1593/strongdog2.git test
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Ensure this PAT is used for pushing changes
