name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Example: Two separate jobs instead of one mega-matrix
  test-job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  test-job-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Single Node version for multi-OS
      - run: npm install
      - run: npm test

  # Additional job for build or packaging
  build:
    runs-on: ubuntu-latest
    needs: [test-job-1, test-job-2]  # Wait for tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

  # Deploy or separate that into its own workflow if it's large
