name: Upload Website to Cloudflare R2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove unwanted files
        run: |
          # Remove the .git directory and other dotfiles that you don't want to deploy
          rm -rf .git
          rm -rf .github  # Remove GitHub workflows
          rm -rf .vscode  # Remove VS Code settings
          rm -f .gitattributes .gitignore

      - name: Upload changed files to Cloudflare R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          source-dir: './'
          destination-dir: './'    # Upload to the root of your R2 bucket
          output-file-url: true    # (Optional) Outputs the file URLs after upload
          multipart-size: 100      # (Optional) File size (in MB) above which multipart upload is used
          max-retries: 5           # (Optional) Maximum number of retries for each multipart chunk
          multipart-concurrent: true  # (Optional) Enable concurrent multipart uploads
          keep-file-fresh: false   # (Optional) Do not delete previous bucket contents
