name: Upload Website to Cloudflare R2

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove unwanted files
        run: |
          # Remove the .git directory and other unwanted dotfiles
          rm -rf .git
          rm -f .gitattributes .gitignore

      - name: Upload changed files to Cloudflare R2
        uses: ryand56/r2-upload-action@master
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          r2-jurisdiction: "WNAM"
          source-dir: './'
          destination-dir: '/'
