name: Upload Website to Cloudflare R2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is available if needed

      - name: Remove Unwanted Files
        run: |
          rm -rf .git .github .vscode
          rm -f .gitattributes .gitignore

      - name: Configure AWS Credentials for R2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cloudflare R2 does not require a region, but this is required by the action
          endpoint-url: https://${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

      - name: Sync Files to Cloudflare R2
        run: |
          aws s3 sync . s3://${{ secrets.CLOUDFLARE_R2_BUCKET }} \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".vscode/*" \
            --exclude ".gitattributes" \
            --exclude ".gitignore"
