name: Upload Website

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update region if needed

      # 3. Find files modified in the last 2 days
      - name: Find recently modified files
        id: changed-files
        run: |
          # Calculate timestamp for 2 days ago
          timestamp=$(date -d "2 days ago" +%s)
          # Find files modified in the last 2 days, excluding specified directories
          find . \( -path "./.git/*" -o -path "./strongdog2/*" -o -path "./strongdog3/*" \) -prune -o -type f -newermt "@$timestamp" -print > changed-files.txt
          # Read files into array and set output
          CHANGED_FILES=()
          while IFS= read -r file; do
            CHANGED_FILES+=("$file")
          done < changed-files.txt
          echo "files=$(printf "%s " "${CHANGED_FILES[@]}")" >> $GITHUB_OUTPUT

      # 4. Upload modified files to S3
      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          if [ -z "${{ steps.changed-files.outputs.files }}" ]; then
            echo "No files modified in the last 2 days."
            exit 0
          fi

          echo "Uploading modified files..."
          for file in ${{ steps.changed-files.outputs.files }}; do
            # Remove leading './' for S3 key
            s3_key=$(echo "$file" | sed 's|^\./||')
            echo "Uploading: $file"
            aws s3 cp "$file" "s3://$AWS_S3_BUCKET/$s3_key" --acl public-read
          done
