name: Update Cards

on:
  workflow_dispatch:
    inputs:
      game_name:
        description: 'Name of the game to add'
        required: true
        type: string

jobs:
  update-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Add New Game to cards-data-test.js
        run: |
          GAME_NAME="${{ github.event.inputs.game_name }}"
          GAME_ENTRY="{ href: 'path-to-game', imgSrc: 'game-image.jpg', name: '${GAME_NAME}', page: 2 },"

          # Append the new game entry to the beginning of cards-data-test.js
          sed -i "1i \ \ \ \ $GAME_ENTRY" cards-data-test.js

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cards-data-test.js
          git commit -m "Add new game: ${{ github.event.inputs.game_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
